const $ = id => document.getElementById(id);
let rounds=[], answers=[], selected=null, sound=false, context, animation, run=0;
function beep(freq=440) { if(!sound)return; try {context??=new (window.AudioContext||window.webkitAudioContext)(); context.resume(); const o=context.createOscillator(),g=context.createGain(); o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.035,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.09);o.connect(g);g.connect(context.destination);o.start();o.stop(context.currentTime+.1);}catch{ } }
function show(id) { ['title-screen','quiz-screen','result-screen'].forEach(s=>$(s).hidden=s!==id);window.scrollTo(0,0); }
function begin() {run++;cancelAnimationFrame(animation); rounds=GameLogic.rounds(GAME_DATA);answers=[];beep(580);show('quiz-screen');renderRound();}
function renderRound() { selected=null; const index=answers.length; $('choices').dataset.palette=String(index); $('round-number').textContent=`${String(index+1).padStart(2,'0')} / 07`; $('progress').replaceChildren(...Array.from({length:7},(_,i)=>{const el=document.createElement('i');el.className=i<index?'complete':i===index?'current':'';return el;})); $('choices').replaceChildren(...rounds[index].map((item,i)=>{const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='radio';input.name='choice';input.value=String(i); const badge=document.createElement('span');badge.className='option-label';badge.textContent=`OPÇÃO ${i===0?'A':'B'}`;const p=document.createElement('p');p.textContent=item.text;const bottom=document.createElement('span');bottom.className='select-line';bottom.innerHTML='<span class="radio-dot"></span><span>ESCOLHER</span>';input.addEventListener('change',()=>{selected=i;document.querySelectorAll('.choice').forEach((c,j)=>c.classList.toggle('selected',i===j));$('next').disabled=false;$('choice-hint').textContent='Escolha feita. Pode avançar!';beep(480);});label.append(input,badge,p,bottom);return label;}));$('next').disabled=true;$('next').textContent='BORA!';$('choice-hint').textContent='Selecione uma opção para continuar'; }
$('start').onclick=begin;$('restart').onclick=begin;
$('next').onclick=()=>{if(selected===null)return;answers.push(rounds[answers.length][selected]);beep(640);if(answers.length===7)finish();else{renderRound();window.scrollTo(0,0);}};
$('home').onclick=e=>{e.preventDefault();run++;cancelAnimationFrame(animation);show('title-screen');};
$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Desativar som':'Ativar som');$('sound').innerHTML=`♪ <span>${sound?'ON':'OFF'}</span>`;beep();};
function finish() { show('result-screen');$('result-actions').hidden=true;$('review-list').hidden=true;$('result-tag').hidden=false;$('result-tag').textContent='CALCULANDO SUA INDECISÃO';$('result-heading').innerHTML='Um lado, outro lado…<br><em>já vamos descobrir.</em>';$('result-detail').innerHTML='<p class="thinking">O ponteiro também está em dúvida<span>...</span></p>';const result=GameLogic.result(answers);const target=result.winner==='lula'?-58:58;const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?120:4600;const start=performance.now(),thisRun=++run;function frame(now){if(thisRun!==run)return;const t=Math.min((now-start)/duration,1);const settle=t*t*(3-2*t);const angle=target*settle+Math.sin(t*32)*72*Math.pow(1-t,1.3);$('needle').style.transform=`rotate(${angle}deg)`;if(t<1)animation=requestAnimationFrame(frame);else reveal(result);}animation=requestAnimationFrame(frame); }
function reveal(result) {$('result-tag').hidden=true;$('result-tag').textContent='';$('result-heading').textContent='Você tem mais tendência a votar no...';$('result-detail').replaceChildren();const name=document.createElement('h3');name.className='winner';name.textContent=String(result.number);const p=document.createElement('p');p.className='score';p.textContent=`Você considerou ${Math.max(result.lula,result.flavio)} de 7 itens do ${result.winner==='lula'?22:13} mais graves.`;const rule=document.createElement('p');rule.className='small-note';rule.textContent='Por isso, o jogo aponta sua tendência para o outro número.';$('result-detail').append(name,p,rule);$('result-actions').hidden=false;beep(780);}
$('review').onclick=()=>{const list=$('review-list');list.hidden=!list.hidden;if(!list.hidden){list.replaceChildren(...answers.map((a,i)=>{const el=document.createElement('article');const heading=document.createElement('strong');heading.textContent=`${i+1}. Item do ${a.candidate==='lula'?'13':'22'}`;const p=document.createElement('p');p.textContent=a.text;el.append(heading,p);return el;}));list.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}};
